# -*- coding: utf-8 -*-
categories = [
    { 'code': 'phim-le', 'title': 'Tất Cả Phim Lẻ' },
    { 'code': 'series', 'title': 'Tất Cả Phim Bộ' },
    { 'code': 'korean-series', 'title': 'Phim Bộ Hàn' },
    { 'code': 'hongkong-series', 'title': 'Phim Bộ Hồng Kông' },
    { 'code': 'us-tv-series', 'title': 'Phim Bộ Mỹ' },
    { 'code': 'documentary', 'title': 'Phim Tài Liệu' },
    { 'code': '18', 'title': 'Phim 18+' },
    { 'code': 'animation', 'title': 'Hoạt Hình' },
    { 'code': 'mystery', 'title': 'Huyền Bí' },
    { 'code': 'sci-fi', 'title': 'Viễn Tưởng' },
    { 'code': '3d', 'title': '3D' },
    { 'code': 'western', 'title': 'Cao Bồi' },
    { 'code': 'war', 'title': 'Chiến Tranh' },
    { 'code': 'family', 'title': 'Thiếu Nhi' },
    { 'code': 'giang-sinh', 'title': 'Giáng Sinh' },
    { 'code': 'comedy', 'title': 'Hài Hước' },
    { 'code': 'action', 'title': 'Hành Động' },
    { 'code': 'crime', 'title': 'Hình Sự' },
    { 'code': 'thriller', 'title': 'Rùng Rợn' },
    { 'code': 'drama', 'title': 'Tâm Lý' },
    { 'code': 'tvb', 'title': 'TVB' },
    { 'code': 'horror', 'title': 'Kinh Dị' },
    { 'code': 'romance', 'title': 'Lãng Mạn' },
    { 'code': 'history', 'title': 'Lịch Sử' },
    { 'code': 'adventure', 'title': 'Phiêu Lưu' },
    { 'code': 'fantasy', 'title': 'Thần Thoại' },
    { 'code': 'thuyet-minh-tieng-viet', 'title': 'Thuyết Minh' },
    { 'code': 'hongkong', 'title': 'Hồng Kông' },
    { 'code': 'india', 'title': 'Ấn Độ' },
    { 'code': 'vietnamese', 'title': 'Việt Nam' },
    { 'code': 'korean', 'title': 'Hàn Quốc' },
    { 'code': 'chuong_trinh-xuan', 'title': 'Chương Trình Xuân' },
    { 'code': 'lossless', 'title': 'Lossless' },
    { 'code': 'liveshow', 'title': 'Liveshow' },
    { 'code': 'mv-chau-a', 'title': 'MV Châu Á' },
    { 'code': 'mv-quoc-te', 'title': 'MV Quốc Tế' },
    { 'code': 'mv-viet-nam', 'title': 'MV Việt Nam' }
]
